# Generated by Django 6.0.4 on 2026-05-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserSubmit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("photo", models.ImageField(upload_to="user_submission/")),
                ("note", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
