# Generated by Django 6.0.4 on 2026-05-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activechaser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activechaser',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activechaser',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
