# Generated by Django 6.0.4 on 2026-05-03 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sonde",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sonde_id", models.CharField(max_length=50, unique=True)),
                ("type", models.CharField(max_length=20, null=True)),
                ("subtype", models.CharField(max_length=20, null=True)),
                ("frequency", models.CharField(max_length=20, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Telemetry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame", models.IntegerField()),
                ("datetime", models.DateTimeField()),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("alt", models.FloatField()),
                ("vel_h", models.FloatField(null=True)),
                ("vel_v", models.FloatField(null=True)),
                ("heading", models.FloatField(null=True)),
                ("temp", models.FloatField(null=True)),
                ("humidity", models.FloatField(null=True)),
                ("pressure", models.FloatField(null=True)),
                ("battery", models.FloatField(null=True)),
                ("f_centre", models.FloatField(null=True)),
                ("snr", models.FloatField(null=True)),
                ("raw", models.JSONField()),
                (
                    "sonde",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tracker.sonde"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["datetime"], name="tracker_tel_datetim_920198_idx"
                    ),
                    models.Index(
                        fields=["sonde"], name="tracker_tel_sonde_i_64789d_idx"
                    ),
                    models.Index(
                        fields=["sonde", "datetime"],
                        name="tracker_tel_sonde_i_749b11_idx",
                    ),
                ],
            },
        ),
    ]
